Fix unit 1.31 compiling with njs 0.8.2
nginx/unit pull request #1027
Opened 2023-12-13 03:31 UTC by drmad

As [@hongzhidao](https://github.com/nginx/unit/discussions/1026#discussioncomment-7837216) noted, Unit 1.31 should use njs 0.8.1. This commit removes two NULL parameter when creating a `struct njs_vm_ops_t` variable in `nxt_script.c`  and `nxt_js.c` to comply with `njs_vm_ops_t` definition in `njs.h` from njs 0.8.2

2023-12-13 12:58 UTC, ac000 reviewed
Hi,

If this is making it work with njs 0.8.2 doesn't it then break it for earlier versions?

Do we have access to the njs version at build time so we could use some `#ifdef`'s to keep it working on < 0.8.2 also?

2023-12-13 14:52 UTC, hongzhidao commented
> If this is making it work with njs 0.8.2 doesn't it then break it for earlier versions?

Unit 1.3.1 should only work with njs 0.8.0 and njs 0.8.1. We need to enhance the document.

> Do we have access to the njs version at build time

Unfortunately, there's no njs version from the library.

2023-12-13 15:15 UTC, ac000 commented
> > If this is making it work with njs 0.8.2 doesn't it then break it for earlier versions?
> 
> Unit 1.3.1 should only work with njs 0.8.0 and njs 0.8.1. We need to enhance the document.

But this patch is making it work with 0.8.2, as per the summary line

```
Fix unit 1.31 compiling with njs 0.8.2
```

> > Do we have access to the njs version at build time
> 
> Unfortunately, there's no njs version from the library.

Hmm, the version is in `njs.h`

```c
#define NJS_VERSION                 "0.8.3"
#define NJS_VERSION_NUMBER          0x000803
```

2023-12-13 15:50 UTC, hongzhidao commented
> But this patch is making it work with 0.8.2, as per the summary line

I haven't reviewed the PR.

> Hmm, the version is in njs.h

I didn't notice it, but thanks for pointing it out.
We discussed if we need to maintain different versions of support of njs. We thought the points:
1. The library hasn't turned into a stable big about its version like 1.0.
2. I feel we can follow the way of nginx njs module which only supports the latest version.

I'd like not to maintain njs version now.

2023-12-13 18:26 UTC, ac000 commented
OK, well I'm just very confused...

The commit summary says

```
Fix unit 1.31 compiling with njs 0.8.2
```

The commit message says

```
As @hongzhidao noted, Unit 1.31 should use njs 0.8.1.
```

These two statements seem at odds with each other. Making it compile with 0.8.2 seems like it will break it for 0.8.1.

2023-12-13 18:42 UTC, ac000 requested changes
Hmm, this is really for 1.32...

I would rather the reference to 1.31 was dropped from the summary line to avoid such confusions...

2023-12-14 01:45 UTC, hongzhidao commented
Agree with Andrew's point.

The code change looks good.
As I understand, this commit is to adjust for njs 0.8.2 structural changes. I would suggest something like this:
```
NJS: adjust for njs 0.8.2 structural changes.

more details
```
Feel free to rewrite it.

2023-12-15 19:02 UTC, thresheek commented
Interestintly I don't have issues building current git HEAD Unit with njs 0.8.2.  Are you talking about non-released njs 0.8.3 yet maybe, e.g. current mercurial version?

2023-12-15 19:06 UTC, thresheek commented
Indeed, the changeset that removes the fields Unit mentions is not in 0.8.2, but in unreleased yet 0.8.3: https://hg.nginx.org/njs/rev/dffdf7c50dfc

2024-01-19 02:14 UTC, hongzhidao commented
Hi @drmad 

> Indeed, the changeset that removes the fields Unit mentions is not in 0.8.2, but in unreleased yet 0.8.3: https://hg.nginx.org/njs/rev/dffdf7c50dfc

I think @thresheek is correct. The njs 0.82 works well, here's the structure.
https://hg.nginx.org/njs/file/45f81882c780/src/njs.h#l242

Would you mind changing the issue title from 0.82 to 0.83?

2024-01-19 02:15 UTC, hongzhidao commented
Hi Timo,
It looks like we only need to check if we should upgrade njs to 0.82. @thresheek, welcome to suggest.
The PR belongs to Unit 1.33.

2024-01-19 02:33 UTC, thresheek commented
I've already proposed a bump for njs to 0.8.2 in https://github.com/nginx/unit/pull/1031 to be shipped with 1.32 so there's that.

2024-02-19 08:08 UTC, hongzhidao commented
Hi all,
Welcome to discuss the new PR https://github.com/nginx/unit/pull/1134 since there are a bit many changes for njs 0.83. We'll have to do more jobs on it.
Thanks.

2024-02-20 13:26 UTC, callahad commented
I've adjusted the title and edited the first message to hopefully clear up some confusion.

2024-02-20 13:47 UTC, ac000 commented
This PR was 'the land of confusion..."

AIUI this PR is superseded by https://github.com/nginx/unit/pull/1134

2024-02-20 14:08 UTC, callahad commented
Ah, yep, that replaces this. Closing as superseded. Thank you, @drman!

2024-02-20 14:08 UTC, closed without merging